version: '3.8'
services:
  microservices:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "/usr/local/bin/wait-for-it.sh ${DB_HOST}:${DB_PORT} -- npx typeorm-ts-node-commonjs migration:run -d src/banner-service/ormconfig.ts && npm run start:prod"
    restart: always
    container_name: hseq_microservices
    ports:
      - "7001:3000"
    env_file:
      - ./.env
    depends_on: []